version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sqlmesh_network
  
  sqlmesh:
    build:
      context: .
      dockerfile: Dockerfile
    image: sqlmesh-image:latest
    container_name: sqlmesh-container
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - sqlmesh_network

  
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:7.3
    environment:
      PGADMIN_DEFAULT_EMAIL : ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD : ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: always

    ports:
      - "5050:80"
    networks:
      - sqlmesh_network

volumes:
  postgres_data:
  pgadmin:
    driver: local

networks:
  sqlmesh_network:
    driver: bridge
